### ISSUE TITLE
[SUGGESTION] Store usernames alongside discord IDs

### ISSUE THREAD

**Issue by Cull-Methi** [coizioc/miniscape#2]
_From @Cull-Methi on October 3, 2018 16:14_

Can be useful (particularly for ~leaderboard) to have this stored.

Given that discord allows you to change your name all willy-nilly we'll need to make sure it updates any time the user updates. Probably do this when commands are issued.

_Copied from original issue: coizioc/math-bot-miniscape#2_

**Comment by coizioc** [comment]
Thanks for the pr.
