### ISSUE TITLE
[BUG] Move instances of using lists for items to use counters instead

### ISSUE THREAD

**Issue by Cull-Methi** [coizioc/miniscape#4]
_From @Cull-Methi on October 3, 2018 16:16_

Instead of having `items = ['coin', 'coin', 'coin', ...]` and sending that to be put in as part of a counter, since we typically know the final number just use a Counter to begin with or feed the Counter object a dict instead

_Copied from original issue: coizioc/math-bot-miniscape#4_

**Comment by coizioc** [comment]
Done.
